[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# broadcast = "broadcast"

# [profile.default.zksync]
# compile = true
# fallback_oz = true
# mode = '3'

# file permissions
ffi = true
fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
    { access = "read-write", path = "../../frontend/utils/Blockchain/foundry/contractAddresses.json" },
    { access = "read-write", path = "./output/example.json" },

]
remappings = [
    "@chainlink/=lib/chainlink/",
    # '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    # '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/',
    '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
